-- AG35C — Drishvara Auth Role Mapping SQL
-- Generated by: vikash vaibhav
-- Boundary:
--   1. Create Auth users manually in Supabase Authentication before running this SQL.
--   2. Do not paste credentials, service-role keys, anon keys or env values here.
--   3. This SQL maps existing auth.users records into public.profiles.
--   4. Admin final authority and Editor assigned-only/no-publish governance are preserved.

insert into public.profiles (id, email, role, display_name, is_active)
select
  u.id,
  u.email,
  'admin',
  'Vikash Vaibhav — Admin',
  true
from auth.users u
where lower(u.email) = lower('dwivedi.vikash.vaibhav@gmail.com')
on conflict (id) do update
set
  email = excluded.email,
  role = 'admin',
  display_name = excluded.display_name,
  is_active = true,
  updated_at = now();

insert into public.profiles (id, email, role, display_name, is_active)
select
  u.id,
  u.email,
  'editor',
  'Vikash Vaibhav — Editor Test',
  true
from auth.users u
where lower(u.email) = lower('vikash4world@gmail.com')
on conflict (id) do update
set
  email = excluded.email,
  role = 'editor',
  display_name = excluded.display_name,
  is_active = true,
  updated_at = now();

select
  email,
  role,
  is_active,
  created_at,
  updated_at
from public.profiles
where lower(email) in (
  lower('dwivedi.vikash.vaibhav@gmail.com'),
  lower('vikash4world@gmail.com')
)
order by role, email;
