-- AG35B — Drishvara Controlled Supabase Schema Package
-- Generated by: vikash vaibhav
-- Boundary:
--   1. This file is safe to commit because it contains no secrets.
--   2. Do not paste service-role key into this file.
--   3. Do not apply this SQL before manual review.
--   4. Auth users are not created in AG35B.
--   5. Public mutation and deployment remain blocked.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null check (role in ('admin', 'editor')),
  display_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.articles (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  subtitle text,
  category text not null,
  status text not null default 'draft' check (
    status in ('draft', 'admin_review', 'returned', 'editor_submitted', 'publish_approved', 'published', 'archived')
  ),
  body_md text,
  excerpt text,
  hero_image_url text,
  hero_image_credit text,
  reference_links jsonb not null default '[]'::jsonb,
  objects jsonb not null default '[]'::jsonb,
  assigned_editor_id uuid references public.profiles(id),
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.article_assignments (
  id uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.articles(id) on delete cascade,
  editor_id uuid not null references public.profiles(id) on delete cascade,
  assigned_by uuid references public.profiles(id),
  assignment_status text not null default 'assigned' check (assignment_status in ('assigned', 'returned', 'submitted', 'closed')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(article_id, editor_id)
);

create table if not exists public.article_audit_logs (
  id uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.articles(id) on delete cascade,
  actor_id uuid references public.profiles(id),
  actor_role text check (actor_role in ('admin', 'editor')),
  action_type text not null,
  before_state text,
  after_state text,
  before_hash text,
  after_hash text,
  decision_note text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.publish_rollback_refs (
  id uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.articles(id) on delete cascade,
  audit_event_id uuid references public.article_audit_logs(id),
  previous_public_artifact_ref text,
  restoration_note text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_articles_status on public.articles(status);
create index if not exists idx_articles_assigned_editor on public.articles(assigned_editor_id);
create index if not exists idx_article_assignments_editor on public.article_assignments(editor_id);
create index if not exists idx_article_audit_logs_article on public.article_audit_logs(article_id);
create index if not exists idx_publish_rollback_refs_article on public.publish_rollback_refs(article_id);

alter table public.profiles enable row level security;
alter table public.articles enable row level security;
alter table public.article_assignments enable row level security;
alter table public.article_audit_logs enable row level security;
alter table public.publish_rollback_refs enable row level security;

drop policy if exists profiles_select_self_or_admin on public.profiles;
create policy profiles_select_self_or_admin
on public.profiles
for select
to authenticated
using (
  id = auth.uid()
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
);

drop policy if exists articles_select_admin_or_assigned_editor on public.articles;
create policy articles_select_admin_or_assigned_editor
on public.articles
for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
  or assigned_editor_id = auth.uid()
);

drop policy if exists articles_insert_admin_only on public.articles;
create policy articles_insert_admin_only
on public.articles
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
);

drop policy if exists articles_update_admin_or_assigned_editor_limited on public.articles;
create policy articles_update_admin_or_assigned_editor_limited
on public.articles
for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
  or (
    assigned_editor_id = auth.uid()
    and status in ('returned', 'draft')
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
  or (
    assigned_editor_id = auth.uid()
    and status in ('returned', 'editor_submitted')
  )
);

drop policy if exists assignments_select_admin_or_assigned_editor on public.article_assignments;
create policy assignments_select_admin_or_assigned_editor
on public.article_assignments
for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
  or editor_id = auth.uid()
);

drop policy if exists assignments_write_admin_only on public.article_assignments;
create policy assignments_write_admin_only
on public.article_assignments
for all
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
);

drop policy if exists audit_select_admin_or_related_editor on public.article_audit_logs;
create policy audit_select_admin_or_related_editor
on public.article_audit_logs
for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
  or exists (
    select 1 from public.articles a
    where a.id = article_id
      and a.assigned_editor_id = auth.uid()
  )
);

drop policy if exists audit_insert_admin_or_assigned_editor on public.article_audit_logs;
create policy audit_insert_admin_or_assigned_editor
on public.article_audit_logs
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'editor')
      and p.is_active = true
  )
);

drop policy if exists rollback_refs_admin_only on public.publish_rollback_refs;
create policy rollback_refs_admin_only
on public.publish_rollback_refs
for all
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_articles_updated_at on public.articles;
create trigger set_articles_updated_at
before update on public.articles
for each row execute function public.set_updated_at();

drop trigger if exists set_article_assignments_updated_at on public.article_assignments;
create trigger set_article_assignments_updated_at
before update on public.article_assignments
for each row execute function public.set_updated_at();
